Legrandin/pycryptodome

setup.py

This fixes #22 by creating the build dir before creating the test file.

Creates build dir before test file. Fixes #22

---

lib/Crypto/PublicKey/DSA.py

* Stumbled upon an import error in the DSA example doctext
* fixed missing self in DSAkey.size

Fix DSS import in DSA doctext example

---

Doc/src/cipher/oaep.rst

`PKCS1_OAP` should be `PKCS1_OAEP`.

Fix typo on OAEP document

---

Doc/src/examples.rst

Fix the names of the AES ciphers in the RSA example.

docs(examples): Fix cipher names

---

lib/Crypto/Cipher/_mode_ctr.py

The format string is interpreting `% bytes` as `%b` instead of the proper `%d`, resulting in an ugly error message:
```
ValueError: unsupported format character 'b' (0x62) at index 29
```

Fix CTR block size error message

---

src/multiply_64.c

As of the v3.5.0 release, I've been unable to uninstall pycryptodome on my macOS Sierra machine running Python 3.6. A coworker experienced the same issue using Anaconda Python 3.6 on High Sierra. The backtrace is super long, but this looks like the relevant part:
```
src/montgomery.c:144:16: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
for (i=0; i<b_words; i++) {
~^~~~~~~~
src/montgomery.c:154:26: warning: comparison of integers of different signs: 'int' and 'size_t' (aka 'unsigned long') [-Wsign-compare]
for (; borrow2>0 && i<a_words; i++) {
~^~~~~~~~
src/montgomery.c:181:16: warning: comparison of integers of different signs: 'int' and 'unsigned long' [-Wsign-compare]
for (i=0; i<elle*2; i++) {
~^~~~~~~ …
```

change addmul128 return type to size_t

---

.travis.yml

This makes Travis build binary wheels on macOS too.
The changes in this PR are not too spectacular, most of the work is done by [🎡cibuildwheel](https://github.com/joerick/cibuildwheel) - actually this was really simple. Please let me know if I forgot something.
I tested a wheel on my MacBook and it appears to be working fine.
Closes: #147

Build wheels on macOS

---

src/montgomery.c

The function posix_memalign is missing on the mingw platform (as well). This patch adds compatibility to the mingw32 and mingw64 platform. See https://www.gnu.org/software/gnulib/manual/html_node/posix_005fmemalign.html

Add mingw(32/64) compatibility

---

Doc/src/signature/signature.rst

I think the example code should look like this:
```
key = ECC.import_key(...)
verifier = DSS.new(key, 'fips-186-3')
hash_object = SHA256.new(data=...)
signature = <the sha256>
verifier.verify(hash_object, signature)
```
Reference: https://www.pycryptodome.org/en/latest/src/signature/dsa.html?highlight=dss#Crypto.Signature.DSS.DssSigScheme.verify

Docs: Call `verify` on the verifier object, not the hash

---

lib/Crypto/Util/_raw_api.py

Util/_raw_api.py:41: DeprecationWarning: the imp module is deprecated in favour of importlib
In fact, the condition was always true whatever the Python version.

Fix use of the deprecated imp module in Python 3

---

lib/Crypto/Util/number.py

Fixes the Python 3 warning:
```python
/Util/number.py:227: DeprecationWarning: invalid escape sequence \ 
"""
/Util/number.py:349: DeprecationWarning: invalid escape sequence \ 
"""
```
I used the same fix as it was done in [requests](https://github.com/requests/requests/pull/3956/files).

Fix DeprecationWarning: invalid escape sequence

---

setup.py

This was missed in https://github.com/Legrandin/pycryptodome/commit/2d2f8bf85a7d09fdc6eeef5ff8e451d689f4e5e9.

Drop support for Python < 2.6

---

Doc/src/contribute_support.rst
pct-speedtest.py

A couple of things missed in https://github.com/Legrandin/pycryptodome/commit/2d2f8bf85a7d09fdc6eeef5ff8e451d689f4e5e9.
Also fix a typo and update some URL redirects.

Drop support for EOL Python 2.4

---

.travis.yml
Doc/src/contribute_support.rst
README.rst
lib/Crypto/Util/_raw_api.py
lib/Crypto/Util/py3compat.py
pct-speedtest.py
setup.py

Subset of #212.
Python 3.0-3.3 are EOL and no longer receiving security updates (or any updates) from the core Python team.
They're also little used.
Here's the pip installs for pycryptodome from PyPI for August 2018:
| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  47.02% |        453,176 |
| 3.6            |  34.38% |        331,425 |
| 3.5            |  12.37% |        119,208 |
| 3.7            |   3.35% |         32,306 |
| 3.4            |   2.68% |         25,803 |
| 2.6            |   0.16% |          1,551 |
| 3.8            |   0.02% |            206 |
| 3.3            |   0.02% |            164 |
| 3.2            |   0.00% |             31 |
| None           |   0.00% |              1 |
| Total          |         | …

Drop support for EOL Python 3.0-3.3

---

lib/Crypto/PublicKey/ECC.py

The private component is referred to as q even though it should be d.

Fix documentation

---

lib/Crypto/Util/_raw_api.py

See:
https://github.com/Legrandin/pycryptodome/issues/228

Work around pycparser bug when optimize=2 is used.

---

compiler_opt.py

MSVC9 distutils ccompiler raises WindowsError, which is not
covered.
File "<string>", line 1, in <module>
File "c:\users\root\temp\pip-install-armnd4\pycryptodome\setup.py", line 445, in <module>
set_compiler_options(package_root, ext_modules)
File "compiler_opt.py", line 325, in set_compiler_options
cpuid_h_present = compiler_has_cpuid_h()
File "compiler_opt.py", line 159, in compiler_has_cpuid_h
return test_compilation(source, msg="cpuid.h header")
File "compiler_opt.py", line 83, in test_compilation
extra_preargs=extra_linker_options)
File "C:\Python27\lib\distutils\ccompiler.py", line 700, in link_executable
debug, extra_preargs, extra_postargs, None, target_lang)
File "C:\Python27\lib\distutils\msvc9compiler.py", line 610, in link
if self._need_link(objects, output_filename):
File …

compiler_opt: Handle msvc/distutils compilation case

---

Doc/src/public_key/dsa.rst

Some notes:
- `f.close()` is needed to make sure the file is actually written (otherwise the `f.read()` below fails)
- `pub_key.verify` throws an NonImplemented exception
- DSS' `verify` throws an exception on errors (and it does not return True/False). Changed accordingly.

Fix code snippet in DSA docs

---

lib/Crypto/Cipher/PKCS1_v1_5.py
lib/Crypto/SelfTest/Hash/common.py
lib/Crypto/Signature/pss.py
lib/Crypto/Util/number.py

Hello,
This is the last patch for this kind of warnings, they should be all fixed now:
```python
/Util/number.py:227: DeprecationWarning: invalid escape sequence \ 
```
I used this command to track them down:
```shell
python3 -Wall -m compileall -q -f *
```
Signed-off-by: Mickaël Schoentgen <contact@tiger-222.fr>

Fix all DeprecationWarning: invalid escape sequence

---

lib/Crypto/Hash/MD2.py

block size of md2 is 16 according to RFC 1319

block size of md2 is 16 according to RFC 1319

---

lib/Crypto/SelfTest/Random/test_random.py

Fixes this warning from Python 3.8:
```
/usr/lib/python3/dist-packages/Cryptodome/SelfTest/Random/test_random.py:103: SyntaxWarning: "is" with a literal. Did you mean "=="?
if sys.version_info[0] is 3:
```

Fix Python 3.8 SyntaxWarning: "is" with a literal

---

lib/Crypto/Protocol/KDF.py

Hello,
Here is a small change to fix:
```python
lib/Crypto/Protocol/KDF.py:556: DeprecationWarning: invalid escape sequence \$
p = re.compile(b'\$2a\$([0-9][0-9])\$([A-Za-z0-9./]{22,22})([A-Za-z0-9./]{31,31})')
```

Fix invalid escape sequence \$ in KDF.py

---

lib/Crypto/SelfTest/Cipher/test_ChaCha20_Poly1305.py
lib/Crypto/SelfTest/Cipher/test_EAX.py
lib/Crypto/SelfTest/Cipher/test_GCM.py
lib/Crypto/SelfTest/Cipher/test_SIV.py

Tests are failing because TestVectorsWycheproof sometimes does not have the "id"
property initialized. This was taken from the (working) Hash/test_CMAC.py

Crypto/SelfTest/Cipher: make sure "id" property exists

---

.travis.yml

Resolves #381.
I ran a test build using my own Travis account, and the `clang` invocations *suggest* the issue is fixed. But the best way to actually test would be to invoke `otool` on the built artifacts. Is there an existing place that builds get pushed, or should I temporarily add Travis artifact uploading to the script?

Fix macOS SDK path for notarization

---

README.rst

The README was using an insecure `http` URL for its homepage link; this PR makes it use `https` instead.

README: Use HTTPS for homepage link

---

lib/Crypto/Cipher/DES3.py

🗝️ length must be 16 or 24 bytes long, not 8

3DES cipher: correct the key length documentation

---

.travis.yml
travis/travis_after_success.sh

Travis-CI allows the creation of aarch64 artifacts.
Make changes in travis scripts, .travis.yml and use manylinux2014 to generate the aarch64 python wheels.
Complete log: https://travis-ci.com/github/janaknat/pycryptodome/builds/182324915
Wheel build job: https://travis-ci.com/github/janaknat/pycryptodome/jobs/380068433

Add aarch64 travis-ci build config

---

lib/Crypto/Cipher/PKCS1_v1_5.py

Closes #555.
I changed line 186 to create a `bytes` object instead of a `bytearray`. As the underlying buffer is passed to C code, it is writable even though `bytes` are read-only from Python.
I additionally repaired the link to Bleichenbacher's paper, as Bell doesn*t host it anymore.

Fix PKCS#1v1.5 not returning bytes

---

lib/Crypto/PublicKey/DSA.py

There is a small typo in DSA.py and check for the primarity of parameter `p` is not working.

Fix parameter check error in DSA construction

---

src/test/test_mont.c

Picked up in Ubuntu:
```
cc -g -O2 -ffile-prefix-map=/<<BUILDDIR>>/pycryptodome-3.11.0+dfsg1=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -O3 -g -fstrict-aliasing -Wall -Werror -msse2 -Wdate-time -D_FORTIFY_SOURCE=2 -I.. -DPYCRYPTO_LITTLE_ENDIAN -DHAVE_POSIX_MEMALIGN -DHAVE_STDINT_H -DSTATIC="" -DHAVE_X86INTRIN_H -DUSE_SSE2 -DHAVE_WMMINTRIN_H -DHAVE_TMMINTRIN_H -DHAVE_UINT128  -o build/test_mont test_mont.c build/mont_32.o build/modexp_utils.o build/siphash.o
test_mont.c:8:5: error: type of ‘mont_select’ does not match original declaration [-Werror=lto-type-mismatch]
8 | int mont_select(uint64_t *out, const uint64_t *a, const uint64_t *b, unsigned cond, unsigned words);
|     ^
../mont.c:260:22: note: type mismatch in parameter 5
260 | STATIC …
```

The final argument to mont_select() is a size_t

---

src/test/Makefile

Debian's build infrastructure detects compiler linking that's missing the expected hardening `LDFLAGS`. It doesn't matter in this case, for tests, but we may as well follow standard C norms, and respect `LDFLAGS` in the C test suite.

Respect LDFLAGS in C tests

---

src/test/make_tests_poly1305_load_m.py

C does not permit 0-length arrays, triggering this warning (raised to an error with `-Werror`) from GCC 11:
```
build/test_poly1305_load_m.c:16:5: error: ‘poly1305_load_m’ reading 1 byte from a region of size 0 [-Werror=stringop-overread]
16 |     poly1305_load_m(m, secret, 0);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

C Tests: Avoid creating a 0-length array

---

src/test/Makefile

Debian and derivatives don't have a `/usr/bin/python` at the moment, the binary is `/usr/bin/python3`. Make it easy to select this when running the C test suite.

Permit easy selection of a python binary in the C test suite

---

.github/workflows/wheels.yml

- Adapted CI to use latest cibuildwheel (2.10.2) for building and testing wheels on supported platforms, using new abi3 support.
- Using new cibuildwheel adds musllinux wheels build, without any extra configuration.
- Kept a tests job for cpXX wheels to use already-built packages.
- Kept a legacy (currently Python 2 and PyPy 3.6) build job using old cibuildwheel.
This also adds 32-bit tests via cibuildwheel, which revealed #669 to me. I've set the 32-bit Python 3 image to `manylinux2014` as a workaround, but it appears to be compatible with older `manylinux1/manylinux2010`.
Apparently `cibuildwheel` silently deprecated PyPy 3.6 in v2.5.0 (no mention in changelog) so I've put it in the legacy job.
Wheel build logs for this PR may be found here (Added a commit on top to disable repo/branch …

Refactor wheel build process (+add musllinux)

---

.github/workflows/codeql-analysis.yml
.github/workflows/integration.yml
.github/workflows/wheels.yml
setup.py

Python 3.11 was [released on 2022-10-24](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk) 🚀 
[![image](https://user-images.githubusercontent.com/1324225/198233993-5b79523b-370f-4316-a4be-9403c8209068.png)](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)

Add support for Python 3.11

---

Doc/src/examples.rst

The examples leave dangling file descriptors for `file_in`.  This PR updates them to close them correctly, as is done for `file_out`.
Alternatively, consider using a context manager.
```
with open("encrypted.bin", "rb") as in_file:
nonce, tag, ciphertext = [in_file.read(x) for x in (16, 16, -1)]
```

Update examples.rst to close file descriptors after use

---

Doc/src/signature/eddsa.rst

Noticed errors in code snippets while learning about EdDSA.
- Fixed references in code snippets to `Crypto.Signature.eddsa.new(key, mode, context=None)` to include missing `mode` parameter.
- Fixed references in code snippets to call sign on EdDSA Signature object, rather than `eddsa` module.

Fixed EdDSA documentation errors in code snippets

---

INSTALL.rst

Updating windows installation instructions, so it is more explicit what the user need to do if they want to install PyCryptodome under Crypto and do the tests.

Updating windows install instructions

---

src/ed25519.c
src/ed448.c

Declarations inside a for loop (e.g.: "for (unsigned i; ;)" ) are only valid in c99 and above.
This change fixes builds on CentOS/RHEL 7, where the compiler default is not c99, and the OS-provided Python 2 does not have -std=c99 in the cflags.

Remove C99 for loop initial declarations.

---

Doc/src/signature/eddsa.rst

The current wording implies that `HashEdDSA` should be avoided if you're not implementing a streaming application (i.e. "_only_ streaming applications should use `HashEdDSA`"). But if I understand the [RFC](https://datatracker.ietf.org/doc/html/rfc8032) correctly, neither is preferable over the other; in fact, `HashEdDSA` is the version that's actually implemented in the RFC.
I changed the wording to instead mention the actual intention; i.e. it's not that `HashEdDSA` is particularly nice for streaming applications, but rather that `PureEdDSA` is particularly bad for streaming applications

Improve wording for EdDSA signing options

---

Doc/src/cipher/chacha20.rst

Link had double `http://http://` and can be updated to `https`

Fix ChaCha20 link

---

lib/Crypto/Util/asn1.py

Use-case: ease semantic creation of optional fields, such as https://www.rfc-editor.org/rfc/rfc5652#section-6.2.4
Brief illustration:
def construct_pwri(encrypted_cek, ke_alg, kdf_alg=None):
recipient = DerSequence([DerInteger(0), ke_alg, DerOctetString(encrypted_cek)])
if kdf_alg is not None:
if kdf_alg._tag_octet != 0xa0:
raise ValueError("keyDerivationAlgorithm is of type [0] IMPLICIT SEQUENCE OPTIONAL")
recipient.insert(1, kdf_alg)
return recipient

Add DerSequence.insert()

---

setup.cfg

This changelog link will be visible on the package's PyPI page.
Also Renovate bot uses this link to provide quicker access to the changelog for a dependency update.

Add changelog URL to package metadata

---

lib/Crypto/SelfTest/PublicKey/test_import_ECC.py

See https://docs.python.org/3.12/whatsnew/3.12.html#removed.

Replace deprecated unittest aliases for Python 3.12

---

Doc/src/cipher/modern.rst

While reading the API docs at https://www.pycryptodome.org/src/cipher/modern#gcm-mode for AES in GCM mode, I noticed an import statement for unpad that wasn't being used.
Patch to remove that import, a minor tweak to be sure.
`make html` appears to build the docs as expected.
Hope this helps!

Remove unused import in GCM decrypt code example.

---

Doc/src/hash/md5.rst

Fixes MD5 docs. Length extension discussion was wrong (quite hilariously in fact).

md5 docs fix

---

src/test/test_mont.c

Hi, I have updated this patch in Debian, because the change that was previously merged has been reverted back. The function name has changed, but the type mismatch issue is still there. Below contains the current patch in Debian:
```
--- a/src/test/test_mont.c
+++ b/src/test/test_mont.c
@@ -5,7 +5,7 @@
int ge(const uint64_t *x, const uint64_t *y, size_t nw);
unsigned sub(uint64_t *out, const uint64_t *a, const uint64_t *b, size_t nw);
void rsquare(uint64_t *r2, uint64_t *n, size_t nw);
-int mod_select(uint64_t *out, const uint64_t *a, const uint64_t *b, unsigned cond, unsigned words);
+int mod_select(uint64_t *out, const uint64_t *a, const uint64_t *b, unsigned cond, size_t words);
void test_ge(void)
{
```
The revision occurred during this …

The final argument to mod_select() is a size_t

---

Doc/src/hash/kmac128.rst
Doc/src/hash/kmac256.rst

While trying the second code example (validate a MAC tag) at https://www.pycryptodome.org/src/hash/kmac256, I noticed that the MAC instance variable name is `mac` and the authentication tag variable name is `mac`, which makes the `mac.verify(mac)` call somewhat confusing.
Won't trip up anyone who is paying attention to be sure, but submitting a patch to change the tag variable name to `mac_tag`, which should clear up any potential confusion. The proposed change follows the precedent in the corresponding Poly1305 code example at https://www.pycryptodome.org/src/hash/poly1305 (which calls the tag variable `mac_tag_hex`).
`make html` appears to build the docs as expected.
Hope this helps!

Change tag variable name in code example to reduce confusion

---

lib/Crypto/Hash/TupleHash128.py
lib/Crypto/SelfTest/Hash/test_TupleHash.py

While documenting issue #767, I noticed a typo (`ValueError` was `ValueErorr`) in `TupleHash.update()`. After fixing typo, I realized that this was dead code (not reachable by calling `update(None)`; likely left over from an earlier version of this function as the existing unit test for `update(None)` expects `TypeError` not `ValueError`.
So, removed the `if data is None` precondition check for `update()` and confirmed unit tests pass.
Also, while I was here, expanded the unit tests to test the happy path for the newly supported ways to pass multiple byte strings as well as a regression test in `test_update_negative()` to catch that `update(tuple)` raises the expected exception.

Expand unit tests for TupleHash.update()

---

Doc/src/signature/dsa.rst

Small commit, noticed some old py2 style `print` statements while copying an example from the DSA docs

Update DSA docs to use Python 3 print

---

Doc/src/signature/pkcs1_pss.rst

While trying the code example (for signing) at https://www.pycryptodome.org/src/signature/pkcs1_pss, I ran into a few exceptions (in Python 3.10). Figured this may be a good time to update this example.
Patch does the following:
- Update `message` to byte string (otherwise `SHA256.new()` throws an exception).
- Update `RSA.import_key()` to read DER file in binary (otherwise this call throws an exception too; plus, `pss.new()` expects a byte string now).
- Removed an unused import statement for `Crypto.Random`.
`make html` appears to build the docs as expected.
Hope this helps!

Update PSS docs for Python 3.

---

lib/Crypto/Hash/CMAC.py

The old documentation said the `hexverify` function is "returning the printable MAC tag". However, it verifies the message with the printable MAC tag. This PR fixes this documentation issue. 
I am unfamiliar with this repository's workflow, but this PR should not require any code checking as a documentation fix without any code modifications. This PR is ready for review.

Fix documentation of Crypto.Hash.CMAC.CMAC.hexverify

---

Doc/src/signature/pkcs1_pss.rst

For completeness sake, update code example for verifying a signature (#783 just updated the signing code example).
Patch does the following:
* Update `RSA.import_key()` to read DER file in binary.
* Remove `TypeError` from except clause.
* Does not appear that verify() should throw this exception; or that the caller is expected to do anything based on API docs at https://www.pycryptodome.org/src/signature/pkcs1_pss#Crypto.Signature.pss.PSS_SigScheme.verify.
* Also, checked the unit tests, the "negative" tests are just checking for `ValueError`.
* Update print statements for Python 3.
`make html` appears to build the docs as expected.
Hope this helps!

Update PSS verify signature code example.

---

src/test/CMakeLists.txt

As requested in issue #774, I added a condition in the CMakeLists so non-x86 can run the test. As I didn't have non-x86 archi, I hope this work.
Also I the opened issue other errors where reported like this one: 
[ 97%] Building C object CMakeFiles/test_aesni.dir/test_aesni.c.o
[...]/src/test/test_aesni.c:2:10: fatal error: wmmintrin.h: No such file or directory
2 | #include <wmmintrin.h>
|          ^~~~~~~~~~~~~
Maybe we should add directive for packages that aren't supported.

fixing CMakeLists for non-x86 architectures

---

Doc/src/examples.rst

example issues fixed. the second 'in one step' should not say hmac_key in comments.

Fix examples.rst minor syntax and doc errors

---

lib/Crypto/Util/number.py

Noticed a typo while reading the documentation for the `isPrime` function that is provided in `Crypto.Util.number`. 
The `returns` section of the function documentation read "`is the input is indeed prime`". The commit in this PR fixes the spelling error to make the sentence grammatically correct by updating it to read "`if the input is indeed prime`".

fix small typo in Crypto.Util.number isPrime returns

---

Doc/src/examples.rst

This typo got introduced with ebfef948b0ca6760885fb19f9e1393886ad2ea48 (Update examples).

Fix typo in example documentation

---

Doc/src/api.rst

This PR adds the missing `h`.
For such change I did not update `Changelog.rst` and `AUTHORS.rst`.

Fix typo in `api.rst`

---

lib/Crypto/Cipher/ChaCha20_Poly1305.py

Removed unnecessary orphaned line (self._len_ct += len(plaintext)) that would raise exception if it were not under the exception raised by the KeyError exception handling.
try:
key = kwargs.pop("key")
except KeyError as e:
raise TypeError("Missing parameter %s" % e)
self._len_ct += len(plaintext)

unnecessary line removed

---

src/make_p256_table.c
src/make_p384_table.c
src/make_p521_table.c

`printf` should not be used with `unsigned` and `%d` specifier. Similarly `int` and `%u` do not go hand in hand. This PR fixes such warnings generated by cppcheck.

Resolve `invalidPrintfArgTypeError`-like warnings

---

lib/Crypto/Protocol/KDF.py
lib/Crypto/SelfTest/Protocol/test_KDF.py

Null bytes to should allowed in the `label` argument of `SP800_108_Counter()` as this is required in some RFCs such as RFC8009 where this is explicitly stated in [key derivation examples](https://datatracker.ietf.org/doc/html/rfc8009#page-13).
[SP.800-108r1](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-108r1.pdf) does not give any indication about what the content of the label is expected to be. This is expected to be defined in the protocol specifications:
> *Label* – A string that identifies the purpose for the derived keying material, which is encoded as a bit string. The encoding method for the Label is defined in a larger context, for example, in the protocol that uses a KDF.

Allow label for SP800_108_Counter to include null bytes

---

src/MD2.c

This PR moves the `assert(hs->count < 16);` _after_ the check if `hs` is not `null`.
Similar to #823.

Avoid null pointer dereference in `md2_digest`

---

Doc/src/public_key/ecc.rst

Missing a comma in one call, format is required in another

Make examples correct

---

lib/Crypto/Math/_IntegerNative.py

The native implementation of `get_bit` returned 0/1 as int while the GMP implementation and the type hint say `get_bit` returns a bool. Wrapped the result of `get_bit` in `IntegerNative` in `bool` to align the three.
See:
https://github.com/Legrandin/pycryptodome/blob/64506f73e9454f441cf2b6f8b2b45cf3c63a0cde/lib/Crypto/Math/_IntegerBase.pyi#L42
https://github.com/Legrandin/pycryptodome/blob/64506f73e9454f441cf2b6f8b2b45cf3c63a0cde/lib/Crypto/Math/_IntegerGMP.py#L635
```py 
IntegerGMP(1).get_bit(1)
> False
IntegerNative(1).get_bit(1)
> 0
```

Update native get_bit implementation to return bool
